[package]
name = "windmenu"
version = "0.5.2"
edition = "2021"

[[bin]]
name = "windmenu"
path = "src/main.rs"


[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
winapi = { version = "0.3.9", features = ["winuser", "shellapi", "wincon", "fileapi", "handleapi", "errhandlingapi", "tlhelp32", "winbase", "wingdi", "libloaderapi", "processthreadsapi", "winnt", "winerror", "wlanapi"] }
